### ISSUE TITLE
Creating a field which is a function of other fields in the same  row

### ISSUE THREAD

**Issue by jan-abt** [brianvoe/gofakeit#374]
####  Ability to refer to a value  of one column  in other columns

```
Person:
  - first_name: Jon
  -  last_name: Doe
  - company_name: ABC
  - email: jon.doe@abc.com
  ```
